### ISSUE TITLE
seg offset problem

### ISSUE THREAD

**Issue by Yuying-Jin** [FrankensteinVariorum/fv-web2023#4]
In f1818 chapter 1, the word `younger` causes seg offset problems. This token disrupts the matching of fv data with other tokens after this token. 
```
My brothers were considerably younger than myself; but I had a friend in one of my schoolfellows, who compensated 
for this deficiency. Henry Clerval was the son of a merchant of Geneva, an intimate friend of my father. 
```

**Comment by ebeshero** [comment]
@Yuying-Jin We are now pretty sure this is due to problems with the first several collation files generated from the original C01 - C10 units--up through 1818 Chapter IV. The problem seems to go away when we look at 1818 Chapter V and onward. So I think if we redo the collation of the first collation units and output files consistently with the rest of the edition, this problem will resolve itself.
